[deps]
obcanonicalradicals = "==0.1.1"
rdkit = ""
xtb = ""
matplotlib = ""
ase = "<3.23"
graphviz = ""
python = ">=3.7,<3.11"
scipy = "<=1.5.4"
numpy = "<2"
autode = ""
rmsd = ""

[pip.deps]
extxyz = "~=0.1.3"
