[deps]
obcanonicalradicals = "==0.1.1"
rdkit = "==2024.09.6"
xtb = "==6.7.1"
libgfortran = "==14.2.0"
matplotlib = ""
ase = "<3.23"
graphviz = "==11.0.0"
python = ">=3.7,<3.11"
scipy = "<=1.5.4"
numpy = "<2"
autode = ""
rmsd = ""

[pip.deps]
extxyz = "~=0.1.3"
